//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace o1Solution.LifeSouthDonor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MergedDonorSource
    {
        public int Id { get; set; }
        public Nullable<int> SourceTableKeyId { get; set; }
        public string DonationSource { get; set; }
        public Nullable<System.DateTime> DriveDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public System.Data.Entity.Spatial.DbGeography LatitudeLongitude { get; set; }
    }
}
